/**
 * Typst PDF Generator
 * Compiles invoice data to PDF using Typst via WebAssembly
 */

import type { Column, Field, Row } from '@/lib/invoice-types'

// Interface for all invoice data needed to generate PDF
export interface InvoicePdfData {
  // Header
  invoiceTitle: string
  invoiceNumber: string
  invoiceNumberLabel: string
  invoiceDate: string
  dateLabel: string
  dueDate: string
  dueDateLabel: string

  // Sections
  fromTitle: string
  fromFields: Field[]
  toTitle: string
  toFields: Field[]
  paymentTitle: string
  paymentFields: Field[]

  // Table
  columns: Column[]
  rows: Row[]

  // Totals
  currencySymbol: string
  subtotal: string
  taxEnabled: boolean
  taxLabel: string
  taxPercentage: string
  tax: string
  discountEnabled: boolean
  discountLabel: string
  discountPercentage: string
  discount: string
  totalLabel: string
  total: string
}

// Escape special characters for Typst strings
// Note: # and $ don't need escaping inside string literals in Typst
function escapeTypst(str: string): string {
  if (!str) return ''
  return str
    .replace(/\\/g, '\\\\')
    .replace(/"/g, '\\"')
}

// Generate Typst source code for the invoice
export function generateTypstSource(data: InvoicePdfData): string {
  // Generate default invoice number if empty
  const now = new Date()
  const year = now.getFullYear()
  const month = String(now.getMonth() + 1).padStart(2, '0')
  const displayInvoiceNumber = data.invoiceNumber || `INV-${year}-${month}`

  // Generate fields list
  const fromFieldsTypst = data.fromFields
    .filter(f => f.value)
    .map(f => `"${escapeTypst(f.value)}"`)
    .join(', ')

  const toFieldsTypst = data.toFields
    .filter(f => f.value)
    .map(f => `"${escapeTypst(f.value)}"`)
    .join(', ')

  const paymentFieldsTypst = data.paymentFields
    .filter(f => f.value)
    .map(f => `"${escapeTypst(f.value)}"`)
    .join(', ')

  // Generate table header cells directly as Typst code
  const tableHeaderCells = data.columns.map(col => {
    const align = col.align === 'left' ? 'left' : col.align === 'right' ? 'right' : 'center'
    return `  table.cell(fill: luma(245), align: ${align})[#text(weight: "semibold", size: 10pt)[${escapeTypst(col.name)}]]`
  }).join(',\n')

  // Generate table data cells directly as Typst code
  const tableDataCells = data.rows.map(row => {
    return data.columns.map(col => {
      const cellValue = row.cells[col.id]
      const align = col.align === 'left' ? 'left' : col.align === 'right' ? 'right' : 'center'

      if (typeof cellValue === 'object' && cellValue !== null) {
        // Description cell with name and description
        const name = (cellValue as { name?: string }).name || ''
        const desc = (cellValue as { description?: string }).description || ''
        let content = ''
        if (name) content += `#text(weight: "medium", size: 10pt)[${escapeTypst(name)}]`
        if (name && desc) content += '#linebreak()'
        if (desc) content += `#text(size: 9pt, fill: rgb("#6b7280"))[${escapeTypst(desc)}]`
        return `  table.cell(align: ${align})[${content}]`
      }

      // Regular cell
      const value = String(cellValue || '')
      if (col.isAmount && value) {
        return `  table.cell(align: ${align})[#text(size: 10pt)[${escapeTypst(data.currencySymbol)}${escapeTypst(value)}]]`
      }
      return `  table.cell(align: ${align})[#text(size: 10pt)[${escapeTypst(value)}]]`
    }).join(',\n')
  }).join(',\n')

  // Calculate column widths
  const colWidths = data.columns.map(col => {
    const width = Number.parseFloat(col.width.replace('%', ''))
    return `${width}%`
  }).join(', ')

  return `// Invoice PDF Generated by Simple Invoice Generator
// Using Typst for high-quality typography

#set page(
  paper: "a4",
  margin: (top: 2cm, bottom: 2cm, left: 2.5cm, right: 2.5cm),
)

#set text(
  size: 11pt,
  fill: rgb("#1a1a1a"),
)

// Brand color - warm gold/terracotta accent
#let accent-color = rgb("#b45309")

// Data
#let invoice-title = "${escapeTypst(data.invoiceTitle)}"
#let invoice-number = "${escapeTypst(displayInvoiceNumber)}"
#let invoice-number-label = "${escapeTypst(data.invoiceNumberLabel)}"
#let invoice-date = "${escapeTypst(data.invoiceDate)}"
#let date-label = "${escapeTypst(data.dateLabel)}"
#let due-date = "${escapeTypst(data.dueDate)}"
#let due-date-label = "${escapeTypst(data.dueDateLabel)}"

#let from-title = "${escapeTypst(data.fromTitle)}"
#let from-fields = (${fromFieldsTypst})
#let to-title = "${escapeTypst(data.toTitle)}"
#let to-fields = (${toFieldsTypst})
#let payment-title = "${escapeTypst(data.paymentTitle)}"
#let payment-fields = (${paymentFieldsTypst})

#let currency = "${escapeTypst(data.currencySymbol)}"
#let subtotal = "${escapeTypst(data.subtotal)}"
#let tax-enabled = ${data.taxEnabled}
#let tax-label = "${escapeTypst(data.taxLabel)}"
#let tax-percentage = "${escapeTypst(data.taxPercentage)}"
#let tax-amount = "${escapeTypst(data.tax)}"
#let discount-enabled = ${data.discountEnabled}
#let discount-label = "${escapeTypst(data.discountLabel)}"
#let discount-percentage = "${escapeTypst(data.discountPercentage)}"
#let discount-amount = "${escapeTypst(data.discount)}"
#let total-label = "${escapeTypst(data.totalLabel)}"
#let total-amount = "${escapeTypst(data.total)}"

// ===== HEADER =====
#grid(
  columns: (1fr, auto),
  gutter: 2em,
  [
    #text(
      size: 42pt,
      weight: "regular",
      fill: rgb("#1a1a1a"),
    )[#invoice-title]
    #v(0.4em)
    #line(length: 3.5em, stroke: 2.5pt + accent-color)
  ],
  [
    #set align(right)
    #set text(size: 10pt)
    #grid(
      columns: (auto, auto),
      gutter: 0.8em,
      row-gutter: 0.5em,
      align: (right, right),
      text(fill: rgb("#6b7280"))[#invoice-number-label],
      text(weight: "semibold")[#invoice-number],
      text(fill: rgb("#6b7280"))[#date-label],
      text(weight: "medium")[#invoice-date],
      text(fill: rgb("#6b7280"))[#due-date-label],
      text(weight: "medium")[#due-date],
    )
  ]
)

#v(2em)

// ===== FROM / TO SECTIONS =====
#grid(
  columns: (1fr, 1fr),
  gutter: 1.5em,
  [
    #block(
      fill: rgb("#fafaf8"),
      stroke: 1pt + rgb("#e7e5e0"),
      radius: 6pt,
      inset: 1.2em,
      width: 100%,
    )[
      #text(size: 12pt, weight: "semibold")[#from-title]
      #v(0.6em)
      #for field in from-fields [
        #text(size: 10pt)[#field]
        #linebreak()
      ]
    ]
  ],
  [
    #block(
      fill: rgb("#fafaf8"),
      stroke: 1pt + rgb("#e7e5e0"),
      radius: 6pt,
      inset: 1.2em,
      width: 100%,
    )[
      #text(size: 12pt, weight: "semibold")[#to-title]
      #v(0.6em)
      #for field in to-fields [
        #text(size: 10pt)[#field]
        #linebreak()
      ]
    ]
  ]
)

#v(2em)

// ===== SERVICES TABLE =====
#table(
  columns: (${colWidths}),
  stroke: none,
  inset: (x: 0.8em, y: 0.6em),
  // Header
${tableHeaderCells},
  // Data rows
${tableDataCells}
)

#line(length: 100%, stroke: 1pt + rgb("#e7e5e0"))

#v(1.5em)

// ===== TOTALS SECTION =====
#align(right)[
  #set text(size: 10pt)
  #grid(
    columns: (auto, 7em),
    gutter: 1.5em,
    align: (right, right),
    text(fill: rgb("#6b7280"))[Subtotal:],
    [#currency#subtotal],
  )

  #if discount-enabled [
    #v(0.4em)
    #grid(
      columns: (auto, 7em),
      gutter: 1.5em,
      align: (right, right),
      text(fill: rgb("#6b7280"))[#discount-label (#discount-percentage%):],
      text(fill: rgb("#16a34a"))[(#currency#discount-amount)],
    )
  ]

  #if tax-enabled [
    #v(0.4em)
    #grid(
      columns: (auto, 7em),
      gutter: 1.5em,
      align: (right, right),
      text(fill: rgb("#6b7280"))[#tax-label (#tax-percentage%):],
      [#currency#tax-amount],
    )
  ]

  #v(0.6em)
  #line(length: 14em, stroke: 1.5pt + rgb("#d1d5db"))
  #v(0.6em)

  #grid(
    columns: (auto, 7em),
    gutter: 1.5em,
    align: (right, right),
    text(size: 13pt, weight: "semibold")[#total-label],
    text(size: 14pt, weight: "bold")[#currency#total-amount],
  )
]

#v(2em)

// ===== PAYMENT DETAILS =====
#block(
  fill: rgb("#fafaf8"),
  stroke: 1pt + rgb("#e7e5e0"),
  radius: 6pt,
  inset: 1.2em,
  width: 100%,
)[
  #text(size: 12pt, weight: "semibold")[#payment-title]
  #v(0.6em)
  #for field in payment-fields [
    #text(size: 10pt)[#field]
    #linebreak()
  ]
]
`
}

// Typst compiler singleton
let typstInitialized = false
// eslint-disable-next-line @typescript-eslint/no-explicit-any
let $typst: any = null

// Initialize Typst compiler
// eslint-disable-next-line @typescript-eslint/no-explicit-any
async function initializeTypst(): Promise<any> {
  if (typstInitialized && $typst) {
    return $typst
  }

  // Dynamic import to avoid SSR issues
  const { $typst: typstModule } = await import('@myriaddreamin/typst.ts/dist/esm/contrib/snippet.mjs')

  // Configure WASM module paths
  typstModule.setCompilerInitOptions({
    getModule: () =>
      'https://cdn.jsdelivr.net/npm/@myriaddreamin/typst-ts-web-compiler@0.6.1-rc5/pkg/typst_ts_web_compiler_bg.wasm',
  })
  typstModule.setRendererInitOptions({
    getModule: () =>
      'https://cdn.jsdelivr.net/npm/@myriaddreamin/typst-ts-renderer@0.6.1-rc5/pkg/typst_ts_renderer_bg.wasm',
  })

  $typst = typstModule
  typstInitialized = true
  return $typst
}

// Generate and download PDF
export async function generateInvoicePdf(
  data: InvoicePdfData,
  filename?: string
): Promise<void> {
  try {
    // Initialize Typst if needed
    const typst = await initializeTypst()
    if (!typst) {
      throw new Error('Failed to initialize Typst compiler')
    }

    // Generate Typst source
    const mainContent = generateTypstSource(data)

    // Compile to PDF
    const pdfData = await typst.pdf({ mainContent })

    if (!pdfData) {
      throw new Error('PDF generation returned empty data')
    }

    // Create download link - convert to ArrayBuffer for Blob compatibility
    const pdfFile = new Blob([new Uint8Array(pdfData)], { type: 'application/pdf' })
    const link = document.createElement('a')
    link.href = URL.createObjectURL(pdfFile)

    // Set filename - use invoice number or generate default INV-YYYY-MM format
    const now = new Date()
    const year = now.getFullYear()
    const month = String(now.getMonth() + 1).padStart(2, '0')
    const defaultInvoiceNumber = `INV-${year}-${month}`
    const invoiceNumber = data.invoiceNumber || defaultInvoiceNumber
    const defaultFilename = `${invoiceNumber.replace(/[^a-zA-Z0-9-]/g, '_')}.pdf`
    link.download = filename || defaultFilename

    // Trigger download
    link.click()
    URL.revokeObjectURL(link.href)
  } catch (error) {
    console.error('Failed to generate PDF:', error)
    throw error
  }
}

// Export for debugging - get the raw Typst source
export function getTypstSource(data: InvoicePdfData): string {
  return generateTypstSource(data)
}
